version: '3'

services:
    
    backend:
        build:
            context: ../
            dockerfile: infra/Dockerfile_backend
        container_name: sample-be
        ports:
          -  "8000:8000"
    
    frontend:
        build:
            context: ../
            dockerfile: infra/Dockerfile_frontend
            args:
              -  API_ADDR=127.0.0.1
        container_name: sample-fe
        depends_on:
          -  backend
        ports:
          -  "3000:3000"
          -  "80:80"
