FROM python:3.8.9-slim

RUN apt update -y
RUN apt install gcc -y
RUN pip install django djangorestframework django-cors-headers uwsgi
WORKDIR sample
COPY backend .

EXPOSE 8000

CMD ["uwsgi", "app.ini"]
