FROM node:10.19.0-slim as build

ARG API_ADDR
RUN apt update -y

WORKDIR frontend

COPY frontend .
RUN npm install
RUN REACT_APP_API_ADDR=${API_ADDR} npm run build

FROM nginx:latest
COPY --from=build frontend/build /usr/share/nginx/html
COPY --from=build frontend/nginx.conf /etc/nginx/conf.d/
RUN rm /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
